### ISSUE TITLE
Erreur sortie 0 - Contaieneur sans log mais ne démarre pas 

### ISSUE THREAD

**Issue by Gniamor** [Gniamor/Cour-H3#1]
Bonjour,
j'ai un souci sur ce containeur il ne démarre pas lorsque je lance le code, le containeur ne donne aucun log
Lorsque j'ai fais un docker build je vois que tout se passe bien, mais ne démarra pas
![Capture d’écran du 2024-09-25 16-16-03](https://github.com/user-attachments/assets/aac02f85-6290-4fa8-9242-87e40d1280fc)
![Capture d’écran du 2024-09-25 16-17-04](https://github.com/user-attachments/assets/cf485c00-701f-481d-8efa-7a6aa502c3d3)

**Comment by bdallard** [comment]
run ton container avec `-it` il devrait te dire l'erreur

**Comment by Gniamor** [comment]
Merci pour le conseil mais comme pour le docker build et les logs, cela ne me resort rien
![Capture d’écran du 2024-09-25 16-27-42](https://github.com/user-attachments/assets/9efe0d88-9544-44d1-bb8e-9caac261214c)

j'ai fait le teste avec un sleep infinity et j'ai perdu mon terminal

![Capture d’écran du 2024-09-25 16-28-02](https://github.com/user-attachments/assets/640ccfad-8172-429c-9763-d31d514e4cd0)

**Comment by bdallard** [comment]
je pense que ton soucis est la : https://github.com/Gniamor/Cour-H3/blob/main/docker-compose/Dockerfile#L5C1-L5C4

**Comment by Gniamor** [comment]
Bonjour, problème résolut
